CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    full_name   VARCHAR(255) NOT NULL,
    role        VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMP    NOT NULL
);

CREATE TABLE tasks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(200)  NOT NULL,
    description  VARCHAR(2000),
    status       VARCHAR(20)   NOT NULL,
    priority     VARCHAR(20)   NOT NULL,
    due_date     DATE,
    owner_id     BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at   TIMESTAMP     NOT NULL,
    updated_at   TIMESTAMP     NOT NULL
);

CREATE INDEX idx_tasks_owner ON tasks (owner_id);
CREATE INDEX idx_tasks_owner_status ON tasks (owner_id, status);
