CREATE TABLE meetings (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(200)  NOT NULL,
    description  VARCHAR(2000),
    location     VARCHAR(255),
    start_at     TIMESTAMP     NOT NULL,
    end_at       TIMESTAMP     NOT NULL,
    owner_id     BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at   TIMESTAMP     NOT NULL,
    updated_at   TIMESTAMP     NOT NULL
);

CREATE INDEX idx_meetings_owner_start ON meetings (owner_id, start_at);

CREATE TABLE meeting_participants (
    meeting_id   BIGINT        NOT NULL REFERENCES meetings (id) ON DELETE CASCADE,
    participant  VARCHAR(255)  NOT NULL
);

CREATE INDEX idx_meeting_participants_meeting ON meeting_participants (meeting_id);
